public class TodayTasks{
      public TodayTasks(){
      takeshower();
      HaveBreakFast();
      CarServicing();
      MovieWithFirlFriend();
}
  
   public static void takeshower(){
   system.debug('I am taking shower');
   }  

    public static void HaveBreakFast(){
   system.debug('I am having BF');
   }  

   public static void CarServicing(){
   system.debug('Car servicing');
   }  

   public static void MovieWithFirlFriend(){
   system.debug('I am on date');
   }  
}